apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-1
  labels:
    app: project-1
  annotations:
    kubernetes.io/ingress.global-static-ip-name: project-1-ip
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: project-1-service
            port:
              number: 8080
